services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///data/app.db
    volumes:
      # Mount source code for development hot reload
      - ./backend/src:/app/src
      - ./backend/data:/app/data
    networks:
      - app-network
    command: ["uvicorn", "src.app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    volumes:
      # Mount source code for development hot reload
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - app-network
    command: ["npm", "run", "dev"]

networks:
  app-network:
    driver: bridge
